### PR TITLE
Build with snappy support

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
```
2021-09-28T23:20:08.4580337Z    INFO (blosc,lib/libblosc.so.1.21.0): Needed DSO lib/libsnappy.so.1 found in conda-forge::snappy-1.1.8-he1b5a44_3
```
seems kinda successful

The issue for me is that python-blosc is actually vendoring its version of blosc. Im trying to address that in
https://github.com/conda-forge/python-blosc-feedstock/pull/40

**Review by ax3l — APPROVED** [review]
LGTM, but I'll wait for a co-maintainer for merge.

**Comment by hmaarrfk** [comment]
I might revive this and push this through.

**Comment by jakirkham** [comment]
Oh thought this was already done in PR ( https://github.com/conda-forge/blosc-feedstock/pull/52 ). Is that not the case?

**Comment by hmaarrfk** [comment]
Yeah. I used my powers to merge this into #52!

**Comment by jakirkham** [comment]
That's fine. Thanks for refreshing this 🙂

**Pull request closed without merging**
