### PR TITLE
NO MRG: Test building with conda-build 2.0.x and conda 4.2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Commit 5960e39 pulls in three packages (ncurses, openssl, and curl) from the jjhelmus/label/bootstrap channel which were copied from the `defaults` channel and support installation into a long prefix environment.  Without these a short (80) character prefix environment is used for the build.

**Comment by jakirkham** [comment]
So I'm unclear on if we can tell if that fixes the issue as upgrading to the newer `conda` seemed to already fix it. Would be worthwhile to drop the `conda` upgrade and see if that still works?

**Comment by jjhelmus** [comment]
> So I'm unclear on if we can tell if that fixes the issue as upgrading to the newer conda seemed to already fix it. Would be worthwhile to drop the conda upgrade and see if that still works?

Nope, using conda `4.1.12` [results in](https://circleci.com/gh/conda-forge/blosc-feedstock/29?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) the `cmake: error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such file or directory` issue

**Comment by jakirkham** [comment]
So it sounds like the fix is just to upgrade `conda` then and it doesn't matter if we rebuild anything, right?

**Comment by jjhelmus** [comment]
> So it sounds like the fix is just to upgrade conda then and it doesn't matter if we rebuild anything, right?

That will result in builds which work but produce packages with a short 80 character prefix.  It is a step forward but more is needed.

**Comment by ocefpaf** [comment]
I think this one is safe to close. Please re-open it I am wrong.

**Pull request closed without merging**
