### PR TITLE
Windows Support

### PR DESCRIPTION
**Pull request by dhirschfeld**
This is just a rebase and update of PR #4 to try and help get it over the line.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
The latest available version in the defaults channel is `1.10.2` which is well over a year old so it would be good to have conda-forge Windows builds working so Windows users can use something more recent.

**Comment by dhirschfeld** [comment]
ping @jakirkham

**Comment by dhirschfeld** [comment]
I used the YAGNI principle to exclude py<35. If there is a demand for other builds, those wanting it will either open an issue or a PR. Until such time, it's probably not worth the maintenance/dev burden to bother with IMHO.

**Comment by jakebolewski** [comment]
Bump.  It would be great to get this over the line.  Happy to help test / cleanup / add anything necessary.

**Comment by jakirkham** [comment]
Should be fixed with PR ( https://github.com/conda-forge/blosc-feedstock/pull/17 ). Builds pending.

**Comment by jakirkham** [comment]
Seems there were some issues with where the DLLs got installed. Tried approach this in PR ( https://github.com/conda-forge/blosc-feedstock/pull/20 ). However have run into a roadblock. As Windows is not my typical platform and generally have too many demands on my time, will need some Windows developers to explore this to unblock it. Please take a look and provide feedback.

**Pull request closed without merging**
