### PR TITLE
Move to conda-forge dependencies

### LINKED ISSUE #18: Use conda-forge dependencies instead of vendoring
Currently we are using `blosc`'s internally vendored dependencies instead of our own. We can fix that though we need to set [some flags]( https://github.com/Blosc/c-blosc/blob/v1.14.0/CMakeLists.txt#L24-L35 ) for the build to switch. Also will need to evaluate what dependencies actually support all platforms and both Windows runtimes.

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #18

### CODE REVIEW

**Comment by zklaus** [comment]
Hm. This seems to work, but I had to cheat: I am copying liblz4.dll to lz4.dll and liblz4.lib to lz4.lib. I did this following the example of zstd because cmake's FindLZ4 was not able to find the library. But if this is the right solution it should probably implemented in the lz4-c-feedstock. Alternatively a patch to c-blocks FindLZ4 maybe able to find the original library.

Any thoughts, @conda-forge/blosc ?

**Comment by jakirkham** [comment]
Thanks for working on this Klaus! 🙏 

> Alternatively a patch to c-blocks FindLZ4 maybe able to find the original library.

Would suggest this route (patch to c-blosc's `FindLZ4.cmake`)

The naming scheme on the part of LZ4 seems [intentional]( https://github.com/lz4/lz4/blob/bdc9d3b0c10cbf7e1ff40fc6e27dad5f693a00e7/lib/dll/example/README.md#lz4-windows-binary-package )

**Comment by zklaus** [comment]
Nice, this seems to work. I just added `liblz4` as a name to the cmake code, which shouldn't have any adverse effects of the other platforms and allows cmake to find the library on Windows.

I consider this ready for full review, @conda-forge/blosc.

Ceterum: I added myself to the maintainers, but feel free to remove me if you prefer.

**Comment by jakirkham** [comment]
Thanks Klaus!

Would it be possible to submit that patch upstream as well? We don't need to wait for it to be accepted. Just getting that process started would be good 🙂

**Comment by hmaarrfk** [comment]
This looks good. ditto on the patch, but it is likely moot with c-blosc2

**Comment by jakirkham** [comment]
Not really c-blosc2 is a breaking change. So things requiring c-blosc will still continue to use it until they can afford to make a breaking change.

**Comment by jorisvandenbossche** [comment]
This seems to break GDAL on macos; we are seeing this in CI builds since a few hours:

```
ImportError while loading conftest '/Users/runner/work/pyogrio/pyogrio/pyogrio/tests/conftest.py'.
pyogrio/__init__.py:1: in <module>
    from pyogrio.core import (
pyogrio/core.py:6: in <module>
    from pyogrio._ogr import (
E   ImportError: dlopen(/Users/runner/work/pyogrio/pyogrio/pyogrio/_ogr.cpython-39-darwin.so, 2): Symbol not found: _ZSTD_compressBound
E     Referenced from: /Users/runner/micromamba/envs/test/lib/libgdal.30.dylib
E     Expected in: /Users/runner/micromamba/envs/test/lib/libblosc.1.dylib
E    in /Users/runner/micromamba/envs/test/lib/libgdal.30.dylib
```

But a rerendering of GDAL might be sufficient?

**Comment by zklaus** [comment]
Ironically, it is precisely an earlier break of gdal that triggered this work, see conda-forge/gdal-feedstock#624.

**Comment by jorisvandenbossche** [comment]
Yes, and it also fixed another GDAL issue (bad interaction with pyarrow using zstd) -> https://github.com/conda-forge/gdal-feedstock/issues/592

**Comment by valeriupredoi** [comment]
hey guys, `blosc` for OSX is giving us a bit of a plonk - I see the new version has undergone a decent diet (went down in size from 1MB to 64kB) - could it be that's now too sexy for our Fiona? :laughing: See https://github.com/ESMValGroup/ESMValTool/issues/2649

**Comment by jakirkham** [comment]
Thanks Klaus! 😀

**Comment by jakirkham** [comment]
Folks can you please raise new issues about any problems run into with the update? This makes these things much easier to track and address

**Comment by jorisvandenbossche** [comment]
I suppose it is the same issue as I mentioned above: https://github.com/conda-forge/blosc-feedstock/pull/53#issuecomment-1122080567

I think (or hope ;)) that https://github.com/conda-forge/gdal-feedstock/pull/624 will solve this.

(as a temporary workaround, you can pin blosc, eg see https://github.com/geopandas/pyogrio/pull/99)

**Comment by hmaarrfk** [comment]
@jorisvandenbossche this seems to be a real issue, though likely unrelated to this particular change.
https://github.com/conda-forge/blosc-feedstock/issues/55

Lets continue the discussion here.

**Comment by valeriupredoi** [comment]
> Folks can you please raise new issues about any problems run into with the update? This makes these things much easier to track and address

@jakirkham absolutely! Was about to open one this morning, I wanted to let things settle a bit since I saw there were bits and bobs still waiting for merge etc - I confirm that the new (6h ago at the time of posting this) `blosc` patch 
```
blosc     1.21.1  h97e831e_2   conda-forge/osx-64   49kB
```
is working fine and is not pissing off `fiona` (in our case) anymore :+1: 

Well done for trimming the package size even more without impacting its functionality - it's usually the other way round - size needs to increase to be working again :grin:

**Comment by jakirkham** [comment]
Glad to hear that. Thanks for the update Valeriu 🙏

**Pull request merged**
