### PR TITLE
Archs: Add ARM64 and PPC64le

### PR DESCRIPTION
**Pull request by ax3l**
Enable further architectures for builds. Officially [supported platforms](https://github.com/Blosc/c-blosc#supported-platforms).

Notes:
- `make` needed explicitly for ARM and PPC images
- PPC64le CMake: https://github.com/Blosc/c-blosc/issues/267
```
CMake Warning at CMakeLists.txt:253 (message):
  Unrecognized system processor ppc64le.  Cannot determine which hardware
  features (GNU 8.2.0) supports, so hardware-accelerated implementations will
  not be available.
```
- ARM64 CMake:
```
CMake Warning at CMakeLists.txt:253 (message):
  Unrecognized system processor aarch64.  Cannot determine which hardware
  features (GNU 7.3.0) supports, so hardware-accelerated implementations will
  not be available.
```

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge/blosc probably ready for a first merge, we can potentially fine-tune additional hardware acceleration later on https://github.com/Blosc/c-blosc/issues/268

**Comment by danielfrg** [comment]
Thats awesome, thanks the PR!

**Comment by ax3l** [comment]
Thanks for merging! :)

**Pull request merged**
