### PR TITLE
version 1.16.3

### LINKED ISSUE #34: Update to 1.16.X
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin please rerender

Closes #34

### CODE REVIEW

**Comment by beckermr** [comment]
@esc for viz

**Comment by beckermr** [comment]
Well at least windows and osx are passing ... :/

Any ideas @conda-forge/blosc?

**Comment by esc** [comment]
@beckermr damn, nothing obvious comes to mind. Will have to take a closer look some other time. Maybe @FrancescAlted knows more?

**Comment by beckermr** [comment]
Bump here @conda-forge/blosc

**Comment by esc** [comment]
@beckermr is there any good documentation for how to reproduce this build locally?

**Comment by beckermr** [comment]
Not really. You need grab the conda-forge pinning file here: https://github.com/conda-forge/conda-forge-pinning-feedstock

Then you can run conda-build w/ it via

```
conda build -m pinnings.yaml recipe
```

This should be close. If you are on a mac, you can use the docker image to build on linux.

**Comment by esc** [comment]
A new version of c-blosc, 1.16.3, has just been released. The failing tests turned out to be volatile and have now been disabled by default. That should make this build successful.

**Comment by beckermr** [comment]
Great. I just bumped 1.16.3 in this PR. 🤞

**Comment by beckermr** [comment]
Hmmmmm. Now windows is failing. Any ideas @esc ?

> Install the project...
-- Install configuration: "Release"
-- Installing: C:/bld/blosc_1552060926037/_h_env/Library/lib/pkgconfig/blosc.pc
-- Installing: C:/bld/blosc_1552060926037/_h_env/Library/bin/msvcp140.dll
CMake Error at cmake_install.cmake:40 (file):
  file INSTALL cannot copy file "C:/Program Files (x86)/Microsoft Visual
  Studio 14.0/VC/redist/x64/Microsoft.VC140.CRT/msvcp140.dll" to
  "C:/bld/blosc_1552060926037/_h_env/Library/bin/msvcp140.dll".
NMAKE : fatal error U1077: 'C:\bld\blosc_1552060926037\_build_env\Library\bin\cmake.exe'

**Comment by esc** [comment]
Issues with the conda-forge builds are now being cross-tracked on the c-blosc repo at:

https://github.com/Blosc/c-blosc/issues/265

Some things to move forwards, that were suggested:

Activate: `CTEST_OUTPUT_ON_FAILURE=1` for all conda-forge builds in general, which should allow us to get more insights in case something goes wrong. Alongside that I would be tempted to reactivate: `DEACTIVATE_SYMBOLS_CHECK=ON` just to see what is going on and if we can maybe fix this build. I mean, the conda-forge recpie builds the c-blosc library in such a way that other tools, such as `python-blosc` can link to it, so the exported shared symbols better be in good working condition.

**Comment by beckermr** [comment]
This looks like a weird conda error though. The code passes tests, but it cannot copy to some windows dir. 

@conda-forge/help-python Do any of you have any ideas here?

**Comment by beckermr** [comment]
Never mind...

**Comment by esc** [comment]
Just a glitch?

**Comment by beckermr** [comment]
Apparently...

**Comment by esc** [comment]
Great! I can see the package on anaconda.org already! Let's hope this will make the python-blosc conda package build too.

**Pull request merged**
